# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

notifications:
  slack:
    on_success: never
    on_failure: always
    secure: "oeUf6u1ADyoJr3r++BE7VwuP9m5jenAS6eCT5mtCX/MKAw2YVjgflyuyou5eANiytUnYhUQXsGZ2Gc8BQ5C7ZSrp5sxpLT9nXKtSpqMBUxlnNKlm71NLO49W/q7Zc4Ie86tMu9yUsAen4hAZUOENwGoZlKHTlKST3p9DJ3em6IIoIApMsrimTBw2Ysnyj3RrCIFYmdKsyRdpn5V2gwcMoVE813ALJiGmC2vq5ixeTGQu+vKvTP1y1pw0S7KpXos6wH+w1Z4BGMzxS+uhuLktAw435etUWaWa60ivVhHBQ1zQWdq/O4pkYAN8VrO2L0krg2d7mNnkxU/Y/dXWyBiTBGHbvL4p8EAG3IKYaygRMLvdR5xehs3e1J6t/4URGZwTOCzq4c0ew/XVtQIRsduqtnZOMmXJEuF20gFSV7IQvKRPV58X9vXtdh1q6zEizfQNDC3TCvdHn6shOP/X1pEbB021H/fI8+GyZenVa3Wt//oE/CDcR+ECn8RlAFGz6atI07zK/5v3bZVvEaMYv66nLd1mGgOvB9+jYgK+8IznVLnKGzQ2Yt+bnqJpVrkeLl6chdLLPLIP1VlgFmyHAzeRd2Pje+UIOM0K6JqdvER2P389bcWaQdD0dvK6djYpx3rTvjtlUmPcqN5ODiqYPFV7mW1Taur9bcWqrLHX91Qnx9I="
    if: type = cron
    
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - TOXENV='test'
        - TOXARGS='-v'
        - TOXPOSARGS=''

matrix:
    include:

        - language: python
          python: 3.6
          name: Python 3.6 and pytest 4.6 (Linux)
          env: TOXENV=py36-test-pytest46

        - os: windows
          name: Python 3.6 and pytest 5.0 (Windows)
          env: PYTHON_VERSION=3.6
               TOXENV=py36-test-pytest50

        - os: osx
          name: Python 3.7 and pytest 5.1 (MacOS X)
          env: PYTHON_VERSION=3.7
               TOXENV=py37-test-pytest51

        - language: python
          python: 3.7
          name: Python 3.7 and pytest 5.2 (Linux)
          env: TOXENV=py37-test-pytest52

        - os: windows
          name: Python 3.8 and pytest 5.3 (Windows)
          env: PYTHON_VERSION=3.8
               TOXENV=py38-test-pytest53

        - language: python
          python: 3.8
          name: Python 3.8 and pytest 6.0 (Linux)
          env: TOXENV=py38-test-pytest60

        - os: osx
          name: Python 3.8 and pytest dev (MacOS X)
          env: PYTHON_VERSION=3.8
               TOXENV=py38-test-pytestdev

install:
    - if [[ $TRAVIS_OS_NAME == osx || $TRAVIS_OS_NAME == windows ]]; then
        git clone git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi

script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS
