name: CI

on:
  pull_request:
  push:
  schedule:
    # Run every Sunday at 04:53 UTC
    - cron: 53 4 * * 0

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.6 and pytest 4.6 (Linux)
            os: ubuntu-latest
            python-version: 3.6
            toxenv: py36-test-pytest46
          - name: Python 3.6 and pytest 5.0 (Windows)
            os: windows-latest
            python-version: 3.6
            toxenv: py36-test-pytest50
          - name: Python 3.7 and pytest 5.1 (MacOS X)
            os: macos-latest
            python-version: 3.7
            toxenv: py37-test-pytest51
          - name: Python 3.7 and pytest 5.2 (Linux)
            os: ubuntu-latest
            python-version: 3.7
            toxenv: py37-test-pytest52
          - name: Python 3.8 and pytest 5.3 (Windows)
            os: windows-latest
            python-version: 3.8
            toxenv: py38-test-pytest53
          - name: Python 3.8 and pytest 6.0 (Linux)
            os: ubuntu-latest
            python-version: 3.8
            toxenv: py38-test-pytest60
          - name: Python 3.9 and pytest 6.1 (MacOS X)
            os: macos-latest
            python-version: 3.9
            toxenv: py39-test-pytest61
          - name: Python 3.9 and pytest dev (Linux)
            os: ubuntu-latest
            python-version: 3.9
            toxenv: py39-test-pytestdev

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: python -m pip install tox
    - name: Run Tox
      run: tox -v -e ${{ matrix.toxenv }}
